### ISSUE TITLE
wireguard no longer exists

### ISSUE THREAD

**Issue by JasperTecHK** [notasausage/pi-hole-unbound-wireguard#2]
um, sudo apt install wireguard no longer seems to work, but wireguard-tools seems to have replaced it?

Also, can't seem to find dkms or modules even after getting the keys and unstable repo loaded. Could you please advise?

**Comment by notasausage** [comment]
Please check the [WireGuard installation instructions](https://www.wireguard.com/install/) for more information about which command(s) are required on which operating systems. On my Raspbian Buster installation, the usual Ubuntu (19.10 and up) command `sudo apt install wireguard` works fine.
