### ISSUE TITLE
Automated Script

### ISSUE THREAD

**Issue by Prajwal-Koirala** [notasausage/pi-hole-unbound-wireguard#3]
Hey I have an automated script is there any way I can add it to this repo??

**Comment by Prajwal-Koirala** [comment]
I have the automated Script,

https://github.com/complexorganizations/wireguard-installer-manager

Is there any way you can add it to this repo??

**Comment by notasausage** [comment]
I'll take a look when I have time, but I'm more interested in keeping the step-by-step flow I already have as this was a learning tool for me and people are welcome to use automated steps if they like, but it wasn't really the point of this project.

**Comment by Prajwal-Koirala** [comment]
Thank you.

**Comment by Prajwal-Koirala** [comment]
> I'll take a look when I have time, but I'm more interested in keeping the step-by-step flow I already have as this was a learning tool for me and people are welcome to use automated steps if they like, but it wasn't really the point of this project.

Any update??
