### ISSUE TITLE
Expanding

### ISSUE THREAD

**Issue by raidoo9** [notasausage/pi-hole-unbound-wireguard#4]
Thanks for putting this together. Im interesting in these additions:

> Move from IPtables (deprecated) to nftables
Add an SSL certificate for the Pi-Hole Web Interface
Get local hostnames working in Pi-Hole so we can see device names instead of local IP addresses

Have you had any progress or enhanced reading links?

Thanks!

**Comment by notasausage** [comment]
I haven't yet, but I need to spend some time on my Pi-Hole setup this weekend because my Raspberry Pi crashed and I had to take it off the network for now.

**Comment by raidoo9** [comment]
Ok, great. Good luck and I will keep an eye out for updates!!!
