### ISSUE TITLE
Can I configure this in my netwrok to run also as a VPN client?

### ISSUE THREAD

**Issue by darellsison** [notasausage/pi-hole-unbound-wireguard#5]
Thanks for the great work you done here.

I have a use case for you, I have a pihole already running off an atomic pi and provides adblocking to my network as it is the main DNS IP. Can I add the wireguard setup also? that way my devices get VPN data from my VPN provider? Any help would be much appreciated.

**Comment by notasausage** [comment]
> I have a pihole already running off an atomic pi and provides adblocking to my network as it is the main DNS IP. Can I add the wireguard setup also? that way my devices get VPN data from my VPN provider?

I would assume this is possible, but I've only setup Wireguard with Pi-Hole on a Raspberry Pi, so I can't answer definitively.
